### ISSUE TITLE
请教这句代码哪错了？？

### ISSUE THREAD

**Issue by githubydl** [jackfrued/Python-100-Days#230]
>>>rt=requests.get("https://baike.baidu.com/item/Python/407313") #这句执行错误，没想明白为什么
Traceback (most recent call last):
  File "<pyshell#173>", line 1, in <module>
    rt=requests.get("https://baike.baidu.com/item/Python/407313")
  File "C:\Users\000\AppData\Local\Programs\Python\Python36\lib\site-packages\requests\api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Users\000\AppData\Local\Programs\Python\Python36\lib\site-packages\requests\api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\000\AppData\Local\Programs\Python\Python36\lib\site-packages\requests\sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\000\AppData\Local\Programs\Python\Python36\lib\site-packages\requests\sessions.py", line 668, in send
    history = [resp for resp in gen] if allow_redirects else []
  File "C:\Users\000\AppData\Local\Programs\Python\Python36\lib\site-packages\requests\sessions.py", line 668, in <listcomp>
    history = [resp for resp in gen] if allow_redirects else []
  File "C:\Users\000\AppData\Local\Programs\Python\Python36\lib\site-packages\requests\sessions.py", line 165, in resolve_redirects
    raise TooManyRedirects('Exceeded %s redirects.' % self.max_redirects, response=resp)
requests.exceptions.TooManyRedirects: Exceeded 30 redirects.
>>> rt=requests.get("https://baike.sogou.com/v58828.htm?fromTitle=Python") #这一句可以执行，为什么上一句出错？

**Comment by AibiTi** [comment]
给 100 块回答这个问题。

**Comment by githchlin** [comment]
99

**Comment by smellsee** [comment]
学编程就要学会自己“瞎折腾”，多试一试，就知道原因了，我给get方法里增加了headers参数，就能够获取到response对象了
`headers = {
				'User-Agent': 'Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36'
			}
bd=requests.get("https://baike.baidu.com/item/Python/407313",headers = headers)`
猜测，是因为搜狗的反爬策略不如百度完备。

**Comment by githubydl** [comment]
> 学编程就要学会自己“瞎折腾”，多试一试，就知道原因了，我给get方法里增加了headers参数，就能够获取到response对象了
> headers = { 'User-Agent': 'Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36' } bd=requests.get("https://baike.baidu.com/item/Python/407313",headers = headers)
> 猜测，是因为搜狗的反爬策略不如百度完备。

感谢感谢。你说得有道理，得自己多想想
