### ISSUE TITLE
使用的python版本是2还是3 

### ISSUE THREAD

**Issue by SeanWang918** [jackfrued/Python-100-Days#63]
使用的python版本是2还是3 ？

**Comment by Sephiroth0705** [comment]
根据Print函数来看，是Python3

**Comment by Roctey** [comment]
3.6  3.7

**Comment by BenSYZ** [comment]
可是我在`pip3 install turtle` 的时候，它报错：

```sh
Collecting turtle
  Using cached https://mirrors.aliyun.com/pypi/packages/ff/f0/21a42e9e424d24bdd0e509d5ed3c7dfb8f47d962d9c044dba903b0b4a26f/turtle-0.0.2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-yvr1vbws/turtle/setup.py", line 40
        except ValueError, ve:
                         ^
    SyntaxError: invalid syntax
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-yvr1vbws/turtle/
```

这样看来这个包不是2的吗，怎么在3上运行起来的，我尝试[修改](https://blog.csdn.net/weixin_38468077/article/details/100785307)后（我是ctrl+z停下来后直接改），在python3.6.9中：

```python
>>>import turtle
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.6/turtle.py", line 107, in <module>
    import tkinter as TK
ModuleNotFoundError: No module named 'tkinter'
```

请问大家是怎么解决turtle这个包的？
